=== zizya33/Servlets/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of types -->
<xs:simpleType name="soilType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="podzolic"/>
    <xs:enumeration value="dirt"/>
    <xs:enumeration value="sod-podzolic"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="color">
  <xs:restriction base="xs:string">
    <xs:enumeration value="white"/>
    <xs:enumeration value="green"/>
    <xs:enumeration value="yellow"/>
    <xs:enumeration value="red"/>
    <xs:enumeration value="orange"/>
    <xs:enumeration value="light green"/>
    <xs:enumeration value="dark green"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="yesNo">
  <xs:restriction base="xs:string">
    <xs:enumeration value="yes"/>
    <xs:enumeration value="no"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="multiplying">
  <xs:restriction base="xs:string">
    <xs:enumeration value="leaves"/>
    <xs:enumeration value="cuttings"/>
    <xs:enumeration value="seeds"/>
</xs:restriction>
</xs:simpleType>

<!-- definition of simple elements -->
<xs:element name="Name">
<xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="Note" type="xs:string"/>
<xs:element name="Soil" type="soilType"/>
<xs:element name="Origin">
<xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="ColorOfStem" type="color"/>
<xs:element name="ColorOfLeaf" type="color"/>
<xs:element name="TemperatureValue" type="xs:short"/>
<xs:element name="Lighting" type="yesNo"/>
<xs:element name="Watering" type="xs:unsignedShort"/>
<xs:element name="Multiplying" type="multiplying"/>
<xs:element name="Value" type="xs:decimal"/>
<xs:element name="Type" type="xs:string"/>

<!-- definition of attributes -->
<xs:attribute name="ID" type="xs:ID"/>

<!-- definition of complex elements -->
<xs:element name="AverageSize">
<xs:complexType>
    <xs:sequence>
      <xs:element ref="Value"/>
      <xs:element ref="Type"/>     
     </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="Temperature">
<xs:complexType>
    <xs:sequence>
      <xs:element ref="TemperatureValue"/>
      <xs:element ref="Type"/>     
     </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="VisualParameters">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="ColorOfStem"/>
      <xs:element ref="ColorOfLeaf"/>   
      <xs:element ref="AverageSize"/>  
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="GrowingTips">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Temperature"/>
      <xs:element ref="Lighting"/>   
      <xs:element ref="Watering"/>  
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="Item">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Name"/>
      <xs:element ref="Note" minOccurs="0"/>
      <xs:element ref="Soil"/>	
      <xs:element ref="VisualParameters"/>
      <xs:element ref="GrowingTips"/>
      <xs:element ref="Multiplying"/>
    </xs:sequence>
   <xs:attribute ref="ID"/>
  </xs:complexType>
</xs:element>

<xs:element name="Flowers">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="Item" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== zizya33/Servlets/src/main/resources/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd">
	<Item ID="id1">
		<Name>Rose</Name>
		<Note>*white rose</Note>
		<Soil>dirt</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>50</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>18</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>700</Watering>
		</GrowingTips>
		<Multiplying>cuttings</Multiplying>
	</Item>
	<Item ID="id2">
		<Name>Violet</Name>
		<Soil>dirt</Soil>
		<VisualParameters>
			<ColorOfStem>dark green</ColorOfStem>
			<ColorOfLeaf>dark green</ColorOfLeaf>
			<AverageSize>
				<Value>15</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>15</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>no</Lighting>
			<Watering>350</Watering>
		</GrowingTips>
		<Multiplying>leaves</Multiplying>
	</Item>
	<Item ID="id3">
		<Name>Carnation</Name>
		<Soil>podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>40</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>16</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>550</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id4">
		<Name>Peony</Name>
		<Soil>podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>55</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>17</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>500</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id5">
		<Name>Chamomile</Name>
		<Soil>sod-podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>70</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>18</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>550</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id6">
		<Name>Iris</Name>
		<Soil>sod-podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>60</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>16</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>640</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id7">
		<Name>Gladiolus</Name>
		<Soil>sod-podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>65</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>16</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>no</Lighting>
			<Watering>370</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id8">
		<Name>Narcis</Name>
		<Soil>sod-podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>45</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>15</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>yes</Lighting>
			<Watering>460</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
	<Item ID="id9">
		<Name>Tulip</Name>
		<Soil>sod-podzolic</Soil>
		<VisualParameters>
			<ColorOfStem>green</ColorOfStem>
			<ColorOfLeaf>green</ColorOfLeaf>
			<AverageSize>
				<Value>55</Value>
				<Type>sm</Type>	
			</AverageSize>
		</VisualParameters>
		<GrowingTips>
			<Temperature>
				<TemperatureValue>15</TemperatureValue>
				<Type>C</Type> 
			</Temperature>
			<Lighting>no</Lighting>
			<Watering>280</Watering>
		</GrowingTips>
		<Multiplying>seeds</Multiplying>
	</Item>
</Flowers>
